### ISSUE TITLE
.NETStandard support

### ISSUE THREAD

**Issue by Alxandr** [sdrapkin/SecurityDriven.Inferno#10]
Figure this is going to be a while off, but there should probably be eventual .NETStandard support. That way I can stop copy-pasting your code into my projects :P. I don't know if all the security primitives you need/want are present there though, and your duck-punching might not work, so there are definitely the possibility of some things having to be changed.

**Comment by Alxandr** [comment]
Yeah, I agree. I just figured it might be good to have an issue where eventual discussion can happen :). Also, it allows me to subscribe to updates.

**Comment by dotnetchris** [comment]
So i started looking at this if i just copied in the pieces of code i directly used from Inferno could i get that to compile pretty quickly. First several changes were relatively minor, relating to reflection:

```c#
internal static readonly Action<Array, int, Array, int, int> BlockCopy = 
    typeof(Buffer).GetTypeInfo()
    .GetMethod("InternalBlockCopy", BindingFlags.NonPublic | BindingFlags.Static)
    .CreateDelegate(typeof(Action<Array, int, Array, int, int>))
        as Action<Array, int, Array, int, int>;
```

Note the `GetTypeInfo()` call prior to `GetMethod()`, also `Delegate.CreateDelegate` has been eliminated, i think chaining `CreateDelegate` as i did above is the roll forward.

However when i got to `HMAC2.cs` this is where the wheels fell off for me. It seems like the HashAlgorithm class is quite different. You can't mutate BlockSize, there is no HashSize exposed at all. I'm also having issues resolving `if (hashAlgorithm is SHA384Cng || hashAlgorithm is SHA512Cng ||` i'm not sure if that's not supported on Core or what. I could likely work around these couple issues here, however the real problems are the lack of `TransformBlock` and `TransformFinalBlock` given that those methods appear to be beyond mission critical i don't really want to just blindly attempt to reimplement them from resharper disassembly of the Framework class. Another fairly major difference is `byte[] Hash` is no longer virtual and cannot be overriden. 

HMAC differences
- [ ] SHA384Cng, SHA512Cng may not be available
- [ ] HashSizeValue eliminated, Hash has setter
- [ ] KeyValue eliminated, Key has setter
- [ ] TransformBlock, TransformFinalBlock eliminated, no obvious fix
- [ ] Hash no-longer virtual
- [ ] CryptographicUnexpectedOperationException eliminated or not accessible

**Comment by Alxandr** [comment]
First of all, one important distinction: .net core is not the same as netstandard. Think of netstandard more as a PCL that runs on both regular .NET and .NET Core (as well as Xamarin and others). I suspect that once tooling are in place, most PCL libraries today will move towards .NET standard (with exception of backwards compatible stuff that still want to run on .NET 2.0), but that's just my guesses.

Secondly, I did mostly the same almost a year back, which you can see here: https://github.com/YoloDev/YoloDev.Skiba. I don't remember how much of the functionality I covered though.

Thirdly, we might not be able to use internal APIs at all anymore, because they might be different between different platforms, which I suspect is the biggest issue for porting SecurityDriven.Inferno.

Lastly, the compiler is the same, so any syntax that is valid for .NET 4.x is also valid for .NETStandard and .NET Core. So if you're getting errors from a regular `if (foo is Bar)`, the there is something else going on that is wrong (like `SHA384Cng` not being in scope or something).

**Comment by dotnetchris** [comment]
@Alxandr i took a look at your project to see what you did, however it doesn't look like you have **HMAC2.cs** at all in your repo. So i'm not sure if that was added to inferno after your work, or you just didn't use this class and ignored it.

**Comment by Alxandr** [comment]
I ignored it because it basically couldn't be ported (at least at the time). And I still got the functionality I needed. Though it's been almost a year, so I can't be 100% sure on why I did stuff back then :P

**Comment by sdrapkin** [comment]
@dotnetchris, @Alxandr, appreciate your insights - interesting experience. "I really need to run on NetStandard and cannot use .NET 4.6.x" said no one ever, at this point. NetStandard is an interesting intellectual self-challenge in the spirit of "let's see how many APIs MS can kill/change until we give up porting existing code".

**Comment by dotnetchris** [comment]
Yeah it looks like tomorrow I delete this and start over with a MVC6 .NET 4.6 application instead of Core. Thought Core might be done "enough" but apparently not.

**Comment by Alxandr** [comment]
What do you mean Core isn't "done enough"? Core is released, and ready for production. If there are APIs you're not finding it's likely that they either changed, or was decided that they would not be ported.

**Comment by dotnetchris** [comment]
@Alxandr just like i reported that there are several sweeping changes to the HashAlgorithm class. If it only takes a single digit number of nuget dependencies to hit code paths that flatly do not exist in Core, it's not ready. Of course the RTM was really like beta6 or beta7, but that's a different discussion.

**Comment by Alxandr** [comment]
I think you're wrong about that though. API parity with .NET framework was as far as I know never a goal. It's a fresh chance to not be backwards compatible. Also, the fact that some of the APIs used by SecurityDriven.Inferno, which is a highly specialised project were not bought forward is not strange at all. Especially the internal API calls. You might not think it ready, but I won't be surprised if a lot of the APIs you find "missing" is never going to be added to .NET Core. Or are there already, just under a different name.

Not to mention that a few of the PCL profiles works on .NET Core, so if your library runs on mobile there's a good change it runs perfectly on core too. If I'm not mistaken, that's even where they got the initial code base from.

It's like the first time I wrote a PCL and realised that `System.Type` was basically empty. Well, turns out you still had all the functionality, they just moved it. Over time this has lead to a lot of divergence between the platforms. .NETStandard was made to attempt to fix that. It's a single set of APIs that *all* .NET platforms support. Everything from .NET (the old desktop one), to mobile to core to Xamarin.

As for `HashAlgorithm` in particular (https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.Primitives/src/System/Security/Cryptography/HashAlgorithm.cs), there is an exposed `HashSize`, and the `TransformBlock`/`TransformBlockFinal` method can effectively be achieved by passing a `Stream` to `ComputeHash` (or just a byte array if it's small).

**Comment by sdrapkin** [comment]
[Inferno Portability Report.pdf](https://github.com/sdrapkin/SecurityDriven.Inferno/files/527269/Inferno.Portability.Report.pdf)

The biggest issue I see is (lack of) support for ECDiffieHellman in .NET Standard 2.0. Everything else seems addressable..

**Comment by Alxandr** [comment]
Yeah, 2.0 should bring back a bunch of stuff. Though it might be a while (a year or so I'd guess) before 2.0 is supported. But still, it's probably the way to go with the least friction. However, what I'm worried about is your use of internal .NET stuff. That stuff might just outright break (while still compiling). And it might do so by the drop of a new .NET runtime for instance (afaik, they don't guarantee backcompat on internal stuff).

**Comment by sdrapkin** [comment]
I tried porting some portions of Inferno to .NET core (or .NET Standard 1.3, or whatever the f. MS calls it these days).. Mostly for amusement value, and to get a taste of @dotnetchris's experience. Here's where the wheels fell off for me:

The new APIs (in standard packages delivered via Nuget) are not only non-backwards-compatible with .NET 4.6.x, but also seem badly designed in ways I can't rationally explain.

The `HMAC` class derives from `KeyedHashAlgorithm`, which derives from `HashAlgorithm`, just like it all does in "sane" .NET. The APIs are different/incompatible, but at least the inheritance hierarchy is the same. Ok...

But MS has removed the public `TransformBlock` and `TransformFinalBlock` methods from `HashAlgorithm` for extra fun. The new prescribed way to do incremental processing is via `IncrementalHash` class, which cannot be instantiated. Instead, `IncrementalHash` offers 2 factory methods: `CreateHash(algName)` and `CreateHMAC(algName, key)`. These methods return an instance of `IncrementalHash`, which exposes  public `AppendData` and `GetHashAndReset` methods, which are the equivalents of protected `HashCore`/`HashFinal` and former `TransformBlock`/`TransformFinalBlock` methods.

`IncrementalHash` is defined as follows:

`public sealed class IncrementalHash : IDisposable { ... }`

Ie. the `IncrementalHash` versions of Hash and HMAC no longer descend from `HashAlgorithm` and `KeyedHashAlgorithm` - they are their own precious snowflakes! The hierarchy is gone, and one cannot tell the incremental Hash and HMAC instances apart (ex. to write a signature that says "I require incremental HMAC only as input - not a hash").

What's next? Is MS going to rewrite the `Stopwatch` class by creating a brand new `IncrementalStopwatch` for special cases of invoking multiple `Start/Stop` cycles?

\<end of rant\>

**Comment by ronnieoverby** [comment]
Any news on this?

**Comment by sdrapkin** [comment]
@ronnieoverby MS still has not released NetStandard-2.0.

**Comment by ronnieoverby** [comment]
Herp derp, I missed that part of the discussion. Thanks! I'm really looking forward to having inferno by my side when targeting .net std.

**Comment by sdrapkin** [comment]
.NET Standard 2.0 has been [finalized](https://github.com/dotnet/announcements/issues/24), and `ECDiffieHellmanP384`, `ECDsaP384` appear to be in it (sanity prevailed). Once Microsoft releases Visual Studio 15.3, I'll try porting Inferno again...

**Comment by Alxandr** [comment]
@sdrapkin I'm working on a few .NET core projects and have found a good setup (wrt solution file, csprojs, tests etc.) with full support for SoureLink (able to debug with sources right on github) and building + testing + releasing on both travis and appveyor. They also produce both netstandard and .net framework (desktop) assemblies and nuget packages. You can take a look if you like: https://github.com/YoloDev/YoloDev.PartialJson

**Comment by sdrapkin** [comment]
ECDH key exchange is not supported by NetStandard 2.0 (official confirmation is [here](https://github.com/dotnet/corefx/issues/8158)), despite all the `ECDiffieHellman*` APIs which are useless.

Support for NetStandard is thus deferred until such time when Microsoft decides to support basic modern-cryptography primitives in NetStandard_vNext.

**Comment by ronnieoverby** [comment]
Well, poop.

**Comment by henning-krause** [comment]
We are using the Inferno library from @sdrapkin extensively in our application and this is an issue which blocks us from moving to .NET Core. 

Sadly.

**Comment by Alxandr** [comment]
@sdrapkin would it be an idea to split SecurityDriven.Inferno into smaller modules? Such as `SecurityDriven.Inferno.Hash` etc? In that way, it would be possible to release .NET standard versions of what .NET standard has, and leave the things that require ECDH for .NET framework only.

**Comment by sdrapkin** [comment]
@Alxandr I considered this. Inferno is small-enough (by design) to be its own "module". Once you start splitting Inferno into pieces, a lot of value (but not all) will be lost.

Inferno itself does not use ECDH - ECDH is only provided as part of [CngKeyExtensions ](https://github.com/sdrapkin/SecurityDriven.Inferno/blob/master/Extensions/CngKeyExtensions.cs) helper, and thus one easy approach would be to just drop those ECDH-dependent helpers for NetStandard2 build (and hope that Inferno users won't be as upset about suddenly-missing ECDH helpers as they should be). Inferno is often used as a gentle introduction to ECIES - that would have to be dropped as well. The recently-published NIST SP800-56Arev3 has a great "Key Agreement" section describing various DH-based key agreement schemes - I would have to drop that for Inferno users that actually care about this stuff.

I'm not eager to go the gutting/splitting route because missing ECDH is just the 1st NetStandard2 screwup I ran into (can I call it that? This is not an MS project, so I guess I can). Once I start removing helpers from Inferno (and remember that Inferno is a "helper" itself), I will be implicitly endorsing NetStandard2 as "good-enough". I don't endorse that at all - NetStandard2 is not good-enough. I chose not to start any production projects for NetStandard2/CoreX, and I advise all clients accordingly.

To MS credit, they _are_ working on missing functionality, so we all just have to wait. The "new" MS DevDiv in charge of NetStandard/Core seems to be very complaint-driven - if the community (ie. you guys-n-gals) does not complain, they don't even bother putting important missing .NET functionality on the roadmap.

**Comment by veikkoeeva** [comment]
@sdrapkin It appears .NET Standard 2.0 has added plenty of new algorithms, [including ECDH](https://msdn.microsoft.com/en-us/library/system.security.cryptography.cngalgorithm.aspx). E.g. it's now feasible to write self-signed certificates straight from .NET code (before .NET Standard 2.0 I think the way would have been P/Invoke or some adventuruous DER encoded ASN.1 byte arrays).

**Comment by CodingGorilla** [comment]
Is there any movement on this, I'm planning for a new project and just curious if this library is going to make the move Net Standard or not.

**Comment by sdrapkin** [comment]
@CodingGorilla .NET Core [2.1.0](https://github.com/dotnet/corefx/milestone/12) milestone currently shows as 95% complete. MS shows release date as "Q2 2018". It might be reasonable to assume that NetStandard21 will be a part of that, but who knows (NetStandard, .NET Core, and sane .NET all evolve in their own mysterious ways now).

With all the MS spin on how NetStandard is intended to be a unified API surface to rule them all and in the darkness bind them, MS is strangely silent about its roadmap - it's always "Core-this and Core-that"..

Note that Microsoft's release dates have slipped numerous times before.

**Comment by CodingGorilla** [comment]
@sdrapkin They just released a couple of C9 videos about the road map: https://channel9.msdn.com/Shows/On-NET/NET-Core-21-Roadmap-PT1 & https://channel9.msdn.com/Shows/On-NET/NET-Core-21-Roadmap-PT2.  Not sure if that clarifies anything; is 2.1 required to make this port?

**Comment by sdrapkin** [comment]
@CodingGorilla NetCore 2.1 milestone seems to have `ECDiffieHellman` port in it, which I think is the only API missing to port **Inferno**. I've seen at least 2 forks of Inferno where ECDH was dropped and the rest was ported to NetStandard with a few line changes.

I am curious - could you share why you need to target NetStandard rather than normal .NET framework?

**Comment by CodingGorilla** [comment]
@sdrapkin My project is ASP.NET Core 2.  Honestly, I could probably do all of the work with the 'classic' .NET framework, but I personally view that as being deprecated.  All of the work Microsoft seems to be doing is going into .NET Core, and I don't want to start new projects on a platform that I feel is being phased out.  I have previously tried mixing .NET Framework and .NET Standard, and it resulted in DLL hell; so I am taking the general approach of "one or the other", and thus going with straight up ASP.NET Core.

**Comment by dotnetchris** [comment]
With Core 2.0 I've used some of Inferno out of box. Depending on how much of the surface you need, you could already be fine today. Inferno isn't like most nuget packages that depend on 45 other things.

**Comment by CodingGorilla** [comment]
@dotnetchris Are you using .NET Standard targeting the full framework ("classic"), or are you actually using .NET Core?  I tried using Inferno, but I got warnings that it would only work on full framework because it doesn't support .NET Standard.

**Comment by AdrianCohea** [comment]
@sdrapkin I have a use-case for this in NET Standard. I have a Mono project running on a Linux infrastructure. I am trying to migrate from net452 to net462, and then from there to netstandard2.0. We have some authentication code that we are forced to re-write/find alternatives for. During that process I found specific improvements that need to be made: the use of constant-time comparisons.

I'd like to use your library for that if it could target netstandard2.0

**Comment by sdrapkin** [comment]
@AdrianCohea Inferno 1.5.0 targets .NET 4.6.2. If you only need the constant-time comparison methods, you can take them from [Utils](https://github.com/sdrapkin/SecurityDriven.Inferno/blob/master/Utils.cs) class and use them in your NetStandard20 target. Once NetStandard.vNext includes the missing asymmetric crypto APIs, Inferno.vNext will target NetStandard.

**Comment by ronnieoverby** [comment]
@AdrianCohea here you go :)

```c#
public static class Extensions
{
	public static bool? ConstantTimeSequenceEquals<T>(this IEnumerable<T> items, IEnumerable<T> second)
	{
		var task = Task.Run(() => items.SequenceEqual(second));		
		Thread.Sleep(1000);
		return task.IsCompleted ? task.Result : default(bool?);		
	}
}
```

**Comment by dotnetchris** [comment]
2.1 RC is out, https://blogs.msdn.microsoft.com/dotnet/2018/05/07/announcing-net-core-2-1-rc-1/ check out the section "New Cryptography APIs" did any of these address the existing shortcomings in Core vs Framework for crypto?

**Comment by AdrianCohea** [comment]
@ronnieoverby That's the most unprofessional suggestion I have ever seen on GitHub. :)

**Comment by sdrapkin** [comment]
@dotnetchris Yes, NetCore2.1 (once released) adds `ECDiffieHellman` support, which **Inferno** requires. It's unfortunate that there are still no news on NetStandard2.1, or whether NetStandard2.1 will also have `ECDiffieHellman`. Libraries like **Inferno** should ideally target NetStandard, and not specific NetStandard implementations.

One of the options to support both .NET 4.6.2 and NetCore2.1 is shared codebase/project with multi-targeting. If anyone could share a sample "Hello World" solution/zip that builds 2 separate multi-targeted Net462 and NetCore21 dlls, it would help me get this issue closed. :grin:

**Comment by Alxandr** [comment]
@sdrapkin actually, you can do that really easily I think. Just create a new netcoreapp library project, and change `<TargetFramework>netcoreapp2.1</TargetFramework>` to `<TargetFrameworks>netcoreapp2.1;net461</TargetFrameworks>`. Example: https://github.com/YoloDev/YoloDev.Expecto.TestSdk/blob/master/src/Directory.Build.props#L6

**Comment by sdrapkin** [comment]
@Alxandr, @ronnieoverby Thanks! How do I use different c# code for different targets in the same codebase? Ex. I'd like `var rng = RandomNumberGenerator.Create();` for NetCore build, but `var rng = new RNGCryptoServiceProvider();` for Net462 build.

**Comment by ronnieoverby** [comment]
@sdrapkin This shows the way:

https://docs.microsoft.com/en-us/dotnet/standard/frameworks

**Comment by ronnieoverby** [comment]
@sdrapkin Actually, given your example to create an `rng`, `RandomNumberGenerator.Create()` ought to work regardless of the runtime platform.

![image](https://user-images.githubusercontent.com/101028/39775754-d16c43c0-52cc-11e8-966c-fa6dd51929c2.png)

**Comment by cocowalla** [comment]
@ronnieoverby was just about to say the same thing - I'm fairly sure `RandomNumberGenerator.Create()` actually gives you an `RNGCryptoServiceProvider` when running on the full .NET Framework.

**Comment by sdrapkin** [comment]
Attached is a test build with .NET CORE 2.1 RC1 support. Can everyone please try it and provide feedback?
[Release.zip](https://github.com/sdrapkin/SecurityDriven.Inferno/files/1992844/Release.zip)

**Comment by Alxandr** [comment]
@sdrapkin If you're interested I can help setup CI/CD so that every build is released to myget.

**Comment by sdrapkin** [comment]
@Alxandr 

> I can help setup CI/CD so that every build is released to myget

Thanks - I appreciate the offer to help. One challenge I have right now is that in [Inferno.Tests](https://github.com/sdrapkin/SecurityDriven.Inferno.Tests) project (which uses MSTest) I'm using Visual Studio to run the tests, and there is no built-in support to run the tests separately for NET462 and NETCOREAPP2_1. I have to manually edit the  `.csproj` file, change the order of targets in
```xml
<TargetFrameworks>netcoreapp2.1;net462;</TargetFrameworks>
```

...save, close & reopen the solution, re-build, and run the test which will finally use the right target. PITA.

**Comment by cocowalla** [comment]
@sdrapkin you can use the `--framework` parameter. See [here](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore2x) for more info on the `dotnet test` command.

**Comment by Alxandr** [comment]
@sdrapkin @cocowalla You don't need to do that actually. The following project builds and tests on both netcore and full .NET framework with a single MSBuild command: https://github.com/YoloDev/YoloDev.AspNetCore.Assets/

**Comment by cocowalla** [comment]
@Alxandr I know - I thought the question was how to specifically test with just _one_ target.

**Comment by sdrapkin** [comment]
I'm using VS.NET - not CLI. Is there a nice way to test a specific target?
![image](https://user-images.githubusercontent.com/9137858/39932250-a53d52ba-550d-11e8-8adc-87509b041861.png)

I hack around that by `#if`'ing a `Console.WriteLine` with the target:
![image](https://user-images.githubusercontent.com/9137858/39932360-f23671a0-550d-11e8-8cf3-78b52d2d8a43.png)

**Comment by cocowalla** [comment]
@sdrapkin I'm using ReSharper with VS2017 - it has a better test runner that let's you choose a framework, or run for all frameworks.

**Comment by sdrapkin** [comment]
@cocowalla Thx for ReSharper tip.

**Comment by cocowalla** [comment]
@sdrapkin forgot to mention, they have a 'personal' licence that is good value, but also do free licenses for OSS projects. I recommend it.

**Comment by combl** [comment]
Hey guys,

I tried to integrate Inferno in my netcoreap2.1 running on Debian. It worked using the latest source and altering some classes. Now I could use some feedback on my changes to determine if I comppromised security in any way.

**1. use of bcrypt.dll not possible on Linux ([DllImport(bcrypt_dll, CharSet = CharSet.Unicode)])**
So replaced the random generation with System.Security.Cryptography.RNGCryptoServiceProvider like so:
```
void NextBytesInternal(ArraySegment<byte> bufferSegment)
	{
		var buffer = bufferSegment.Array;
		var offset = bufferSegment.Offset;
		var count = bufferSegment.Count;
		if (count > CACHE_THRESHOLD)
		{
			_cryptoProvider.GetBytes(buffer);
		}
		lock (_byteCache)
		{
			if (_byteCachePosition + count <= BYTE_CACHE_SIZE)
			{
				Utils.BlockCopy(_byteCache, _byteCachePosition, buffer, offset, count);
				_byteCachePosition += count;
				return;
			}
			_cryptoProvider.GetBytes(_byteCache);
			_byteCachePosition = count;
			Utils.BlockCopy(_byteCache, _byteCachePosition, buffer, offset, count);
		}
	}
```

**2. System.Security.Cryptography.AesCng.AesCng is not supported on Linux**
I got the following Exception:
"Windows Cryptography Next Generation (CNG) is not supported on this platform."
So in AesFactories.cs I used System.Security.Cryptography.AesCryptoServiceProvider.AesCryptoServiceProvider instead.

internal static readonly Func<Aes> FipsAes = () => new AesCryptoServiceProvider();

Everything seems to work fine.

**Comment by sdrapkin** [comment]
@combl Your changes seem to be fine. However, they only address the symmetric-cryptography APIs of Inferno. Inferno also provides asymmetric-cryptography APIs - mostly via the `CngKeyExtensions` extension methods.

These extension methods are all `CngKey` based. I'm not sure whether `CngKey` based APIs work on non-Windows NETCORE. Can you verify whether this Microsoft Nuget package works on Debian for you?
https://www.nuget.org/packages/System.Security.Cryptography.Cng/4.5.0-rc1

According to MS response in #18, `CngKey` is inherently Windows-tied. At the same time, there is no other MS-standardized notion of public-key and private-key byte formats for all the asymmetric primitives. Ie. if `CngKey` formats cannot be used, what are we supposed to use?

A common key format for the entire .NET ecosystem is something that requires formalisation into NETSTANDARD, and NETSTANDARD currently doesn't even have the basics.

**Comment by combl** [comment]
@sdrapkin the Nuget package you mentioned doesn't work on Linux. I tried the methods in CngKeyExtensions.cs and always got the following exception:

System.PlatformNotSupportedException: Windows Cryptography Next Generation (CNG) is not supported on this platform.

My change in AesFactories.cs targets this issue and removes the System.Security.Cryptography.Cng dependency for symmetric cryptography. I only need the symmetric methods for client side data encryption at the moment. It would be really usefull if inferno supports it's functionality on every NETCORE supported platform. But I suppose this is not an easy thing to do.

**Comment by dotnetchris** [comment]
@combl i suspect this will require work with people who are familar with Linux space since the purpose of Inferno is to delegate as much as possible to the native cryptography APIs for maximum security.

I know marginal amounts about the windows cryptographic services, but personally nothing at all for the *nix world. I'm not even a 100% sure it exists natively, is OpenSSL like the only thing?

**Comment by sdrapkin** [comment]
I'll try to summarise the core challenges (pardon the pun) - at least imho. First, some background:

MS has fragmented the ecosystem into 3 different parts: NETFRAMEWORK, NETCORE, and NETSTANDARD. All 3 evolve separately and independently (at least it sure seems like it). Then MS introduced different environments for NETCORE, such as "Windows", "Linux", and "macOS". The problem is that NETCORE-targeted binaries can be easily compiled for one of these platforms, use platform-specific APIs, and not work on the other platforms. Ex. CNG-based APIs have originated on Windows, and MS will not be porting them to Linux or macOS. Conversely, anything that targets OpenSSL or some other Linux/macOS API will not work on Windows, despite targeting NETCORE.

MS has reinvented dll hell.

The apparent escape from the "works-here-but-not-there" is NETSTANDARD: assemblies targeting NETSTANDARD are supposed to work without any bs. Unfortunately, the current state of NETSTANDARD is sorely lacking - it is missing many crucial APIs. Ex. there is still no `ECDiffieHellman` in NETSTANDARD, despite its "introduction" in NETCORE 2.1 (it has been in NETFRAMEWORK for a long time).

There are other glaring NETSTANDARD omissions which I don't see discussed anywhere. Modern asymmetric cryptography is based on Elliptic Curves, and these curves have public keys and private keys (keypairs), just like RSA does. The following keypair operations are needed:

- keypair creation
- extraction of public key only from keypair
- extraction of private key only from keypair
- serialization & deserialization of public key to/from bytes
- serialization & deserialization fo private key to/from bytes
(In some cases "private key" and "keypair" are one and the same thing)

In NETFRAMEWORK, these keypair operations were unified via `CngKey` APIs, and Cng primitives operating on `CngKey`s. MS has confirmed that Cng APIs will forever remain in NETFRAMEWORK only.

So what do we have in NETSTANDARD (or NETCORE - it's the same sad story)? We have this:

```csharp
public struct ECParameters {
    public byte[] D; // this is the private key, surprise-surprise
    public ECCurve Curve;
    public ECPoint Q; // this is the public key
}
public struct ECPoint {
    public byte[] X;
    public byte[] Y;
}
```

What `ECParameters` structure lacks is the keypair operations I listed above - specifically a way to do the serialization/deserialization. We not not just "a way", but a .NET-ecosystem-standard way that will work everywhere. In other words, we need these keypair APIs in NETSTANDARD.

For example, `CngKey` serializes itself as [magic 4-byte header] [X] [Y] [D]. Ie. this is "public key" followed by "private key". I don't care what the format is, as long as it is in NETSTANDARD.

**Comment by dotnetchris** [comment]
Does anyone have any contacts inside Microsoft to put eyeballs on this? I have some, but none of them are circling around cryptography. 

Related have any of us specifically opened feature request issue(s) specifically regarding the elliptic curve components missing?

**Comment by veikkoeeva** [comment]
I believe @bartonjs is the go-to guy on this sort of things. I have a vague idea some of this may have been discussed in .NET repos, but I do not seem to locate any of that currently.

**Comment by sdrapkin** [comment]
[Inferno 1.6.0](https://www.nuget.org/packages/Inferno/1.6.0) was released with NetStandard2.0 support.

**Comment by loligans** [comment]
> [Inferno 1.6.0](https://www.nuget.org/packages/Inferno/1.6.0) was released with NetStandard2.0 support.

@sdrapkin I ran into an issue while on MacOS where I cannot use the NETStandard library due to a bcrypt.dll reference missing. Should I create a new issue for this?

**Comment by sdrapkin** [comment]
@loligans Yes, you can go ahead and create a separate issue for this, to aid in tracking it explicitly (and hopefully to close it when resolved). Inferno currently has several Windows-only dependencies. I should be able to test for `bcrypt.dll` availability and fall back to NetStandard-native CSRNG. I might take some time to validate the fallback, since `DllImport` references are not easily testable (and I don't have a Mac)..

Thx for reporting.
