### ISSUE TITLE
Targeting 4.5.1

### ISSUE THREAD

**Issue by RaptorCZ** [sdrapkin/SecurityDriven.Inferno#12]
Is it possible to get sources and retarget back to 4.5.1 or there is any breaking change? We want to use Inferno in 4.5.1 application. We can't switch to 4.5.2.

**Comment by sdrapkin** [comment]
.NET 4.5.1 has been unsupported by Microsoft since January 12, 2016. You can always download Inferno source code and recompile yourself for .NET 4.5.1.
