### ISSUE TITLE
Missing ArgumentNull checks in Utils.ConstantTimeEqual

### ISSUE THREAD

**Issue by Tornhoof** [sdrapkin/SecurityDriven.Inferno#13]
Wrong exception type in Utils.ConstantTimeEqual if arguments are null

Steps to reproduce:
1. Run Utils.ConstantTimeEqual("Hello World", null);
2. Run Utils.ConstantTimeEqual(new byte[] {0}, null);

Actual: NullReferenceException
Expected: ArgumentNullException

I know that your comments include "// Null checks of "x" and "y" are skipped. Appropriate exceptions will be raised anyway.". These methods are public API, they should throw ArgumentNullException, simply because it's a.) the expected behaviour and b.) NullRefException does not tell you which argument is null.

Please add appropriate ArgumentNullException handling to these methods.

**Comment by sdrapkin** [comment]
`NullReferenceException` is thrown in `ConstantTimeEqual` to indicate that it is caller's responsibility to ensure non-nullness of caller-provided arguments. Callers that have already insured non-nullness of arguments are not perf-penalized with an extra check.  Callers that are less strict with their input validation will not create a security vulnerability (exception _will_ be thrown) and will do explicit null checks.

I believe that the current approach strikes a good balance between performance and security in this case (will not be adding additional null checks that throw `ArgumentNullException`). I'll update documentation to make it clear what exception gets thrown if the arguments are null.

**Comment by Tornhoof** [comment]
Thanks for your explanation. That's fine for me.
