### ISSUE TITLE
ToBytes/FromBytes issue with Unicode characters

### ISSUE THREAD

**Issue by LRomano72** [sdrapkin/SecurityDriven.Inferno#15]
Hi,

Not sure this is an issue but I was using your ToBytes and FromBytes as I was being lazy and wanted to avoid the assumption of UTF-8 encoding or any encoding at all. From your documentation it sounds like that functions are encoding agnostic so I tried to use them as so:
        public string Encrypt(string message, string password)
        {
            var secretMessage = new ArraySegment<byte>(message.ToBytes());
            return SuiteB.Encrypt(password.ToBytes(), secretMessage).FromBytes());
//Code that I use now:
//            var secretMessage = new ArraySegment<byte>(Encoding.UTF8.GetBytes(message));
//            return Convert.ToBase64String(SuiteB.Encrypt(Encoding.UTF8.GetBytes(password), secretMessage));
        }

The goal is to have a simple helper so the caller uses strings and doesn't pass around Byte[].
Then I did a unit test with where I passed in Unicode characters and the error at the end of the method would be:
System.Text.EncoderFallbackException: Unable to translate Unicode character \uD97C at index 1321 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)
   at System.Text.UTF8Encoding.GetByteCount(Char* chars, Int32 count, EncoderNLS baseEncoder)
   at System.Text.UTF8Encoding.GetByteCount(String chars)
   at System.IO.BinaryWriter.Write(String value)
   at Microsoft.Build.BackEnd.NodePacketTranslator.NodePacketWriteTranslator.TranslateDictionary(Dictionary`2& dictionary, IEqualityComparer`1 comparer)
   at Microsoft.Build.Execution.BuildParameters.Microsoft.Build.BackEnd.INodePacketTranslatable.Translate(INodePacketTranslator translator)
   at Microsoft.Build.BackEnd.NodePacketTranslator.NodePacketWriteTranslator.Translate[T](T& value, NodePacketValueFactory`1 factory)
   at Microsoft.Build.BackEnd.NodeConfiguration.Translate(INodePacketTranslator translator)
   at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.NodeContext.SendData(INodePacket packet)

So the question is, do these extensions work with Unicode chars or not? I assumed that your meaning of "encoding agnostic" mean that it placed it into some byte format that could handle any type of characters but could just be my misunderstanding.

Unit test looks like this:
    [TestClass]
    public class AesSuiteBEncryptionTests
    {
        string encryptionKey = "C932B484-2D79-4A98-9348-CC3C6A18C9A8";

        [TestMethod]
        public void Encrypt_Then_Decrypt_WithPassword_Happy_Path()
        {
            //Arrange
            IAesEncryption encryptor = new AesSuiteBEncryption();

            //Items with Chinese and unicode chars
            string textMessage = "据検金身際線命知法屋売更気駅爆生要。Darfst gar mich und ja nacht gezagt stürmten geträumt mein liebe o die du du lange ruft mut deine treibt spät oft glück es mit mich du schönen brust nicht wo sie seufzer der verwundert dich vögel sie mutter gar liebe nicht schmilzt ich dich denkst grambefangen wie schaust weiter geliebet du wiedersehn vaterland deine laue friedlich du du lange du warum zu oft wo lachtet der sanft es es dich du verwundert in es du verwundert nicht verschwiegen nacht blieb du gar so ein gartens du ist ferne beiden ward der nicht deine deinen warum doch nicht sanftes zürntest dich hab lachtet es mutter mund vom jedoch ihr du bist dich lachtet deinen verschwiegen hab wie großer gerne mal";
            
            //Act
            //encryption
            var encryptedText1 = encryptor.Encrypt(textMessage, encryptionKey);
            var encryptedText2 = encryptor.Encrypt(textMessage, encryptionKey);

            //Display Text to see it they are different
            Debug.WriteLine(encryptedText1);
            Debug.WriteLine(encryptedText2);

            //decryption
            var decryptedText1 = encryptor.Decrypt(encryptedText1, encryptionKey);
            var decryptedText2 = encryptor.Decrypt(encryptedText2, encryptionKey);

            //Display Text to see it they are different
            Debug.WriteLine(decryptedText1);
            Debug.WriteLine(decryptedText2);

            //Assert
            Assert.AreNotEqual(encryptedText1, encryptedText2);
            Assert.AreEqual(decryptedText1, decryptedText2);

        }
}
Any info would be great and thanks for the great library.

**Comment by sdrapkin** [comment]
@LRomano72 You are calling `SuiteB.Encrypt(...)` which returns a `byte[]` and then you are passing that `byte[]` into `.FromBytes()` which returns a string.

The confusion is likely due to an assumption that `.FromBytes()` is able to convert *any* `byte[]` into a string.

`.ToBytes()` and `.FromBytes()` are a pair of `byte[]`-to-string serialization/deserialization methods. `.FromBytes()` can only deserialize into a string what `.ToBytes()` has serialized into a `byte[]` - not any random `byte[]` like you might get out of `SuiteB.Encrypt(...)`. There are no string-input restrictions/assumptions on `.ToBytes()`, but `.FromBytes()` can only process what `.ToBytes()` has produced.

If you want to convert any random `byte[]` into a string and back, you should use
 `.ToB64Url()` and `.FromB64Url()`.

I hope the above is helpful and I understood the issue correctly..

**Comment by LRomano72** [comment]
Ok I see where I messed up. Thanks for the information and help. Going to test it out now.

**Comment by Erutan409** [comment]
@sdrapkin I just came to this realization by going through the source code and reverse-engineering what this was doing. Then finding this cemented my understanding.

I'd strongly encourage you to note this, explicitly, on in your documentation/website.
