### ISSUE TITLE
There's no nuget package?

### ISSUE THREAD

**Issue by rjcarneiro** [sdrapkin/SecurityDriven.Inferno#16]
Hi,

It would be amazing if there was created a nuget package in nuget.org so we could include the package directly in our projects.

**Comment by Insire** [comment]
https://www.nuget.org/packages/Inferno.StrongName/

https://www.nuget.org/packages/Inferno/

![grafik](https://user-images.githubusercontent.com/11455827/38892237-fdbf493c-4286-11e8-8985-b1bcff0e53d8.png)

**Comment by rjcarneiro** [comment]
How did I miss that? 

Many thanks 🙏🏼
