### ISSUE TITLE
Examples of using PBKDF2

### ISSUE THREAD

**Issue by cmatskas** [sdrapkin/SecurityDriven.Inferno#2]
Hi,
Is your inclusion of PBKDF2 just the standard library of the .NET implementation or did you create a wrapper around the class? Could you include some samples or maybe even unit tests that could show how to use it?
Thanks,
CM

**Comment by sdrapkin** [comment]
The PBKDF2 code is not a wrapper around [Rfc2898DeriveBytes](https://msdn.microsoft.com/en-us/library/system.security.cryptography.rfc2898derivebytes%28v=vs.110%29.aspx). It is a reimplementation which uses the source of Microsoft's implementation with some tweaks (to optimize performance and to support HMAC factories).

You can find plenty of usage examples and test vectors in [SecurityDriven.Inferno.Tests](https://github.com/sdrapkin/SecurityDriven.Inferno.Tests).

**Comment by cmatskas** [comment]
Thanks @sdrapkin. I missed the one massive file with all the tests! Apologies for this. I suppose it makes sense and I like your re-implementation. I will make sure I use it on my next project that requires security baked in. Keep up the good work and feel free to close this issue :)
