### ISSUE TITLE
License info not on Nuget.org

### ISSUE THREAD

**Issue by ymccready** [sdrapkin/SecurityDriven.Inferno#25]
Hello,
Minor suggestion here. Would it be possible to add the license info directly on the Nuget.org page? I think this is normally done via the License section of the Nuspec file ([see reference](https://docs.microsoft.com/en-us/nuget/reference/nuspec)).
I looked for the NuSpec file to submit PR, but could not find it. 

Automated tools (BlackDuck for example) are scraping this information, but since it's not there, your lib appears as "license unknown" in these tools because of that. 

Thanks for the work! 
Cheers,

**Comment by sdrapkin** [comment]
I've updated nupkg file (not on Github) to include the `<licenseUrl>` link.
New releases will include it.

**Comment by ymccready** [comment]
That's great. Thanks!
