### ISSUE TITLE
Release strong named nuget packages for newer versions

### ISSUE THREAD

**Issue by ThoughtHopper** [sdrapkin/SecurityDriven.Inferno#26]
I have read the issue:
Issue (https://github.com/sdrapkin/SecurityDriven.Inferno/issues/6)

I apologize but I find myself in the same boat as other people.

Having stated my situation, I'd like to request some sort of automation, so that future updates trigger two nugets releases, the regular one and the strong named one.

Thank you

**Comment by sdrapkin** [comment]
I will release strong-named nuget packages for newer versions.
