### ISSUE TITLE
Could not load file or assembly System.Numerics.Vectors.dll

### ISSUE THREAD

**Issue by okvalsralos** [sdrapkin/SecurityDriven.Inferno#29]
If targeting .NET 4.6.2 and building in release mode there is an

>SGEN : error : An attempt was made to load an assembly with an incorrect format: C:\Users\johndoe\\.nuget\packages\system.numerics.vectors\4.5.0\ref\net46\System.Numerics.Vectors.dll.
>    - Could not load file or assembly 'file:///C:\Users\johndoe\\.nuget\packages\system.numerics.vectors\4.5.0\ref\net46\System.Numerics.Vectors.dll' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)
>    - Cannot load a reference assembly for execution.

Version of `System.Numerics.Vectors.dll` in .NET 4.6.2 is 4.1.3.0.

Found a similar issue and a possible solution for the NuGet package: https://github.com/vpenades/SharpGLTF/issues/4#issuecomment-495515684

The `Inferno.StrongName` doesn't produce the issue and there is no reference in NuGet package to `System.Numerics.Vectors.dll`

![NuGetPackageExplorer_GaI4BFLS2U](https://user-images.githubusercontent.com/18552770/69735019-427fde00-1130-11ea-8b3a-db562120cbd2.png)

**Comment by sdrapkin** [comment]
[ConsoleApp1.zip](https://github.com/sdrapkin/SecurityDriven.Inferno/files/3898398/ConsoleApp1.zip)

I'm attaching a console-app repro. Opened VS.NET-2019; new console app targeting .NET 4.6.2. Added "SecurityDriven.Inferno 1.5.3" from Nuget, which also asked to install Numerics.Vectors.

The repro runs fine for me. Can you please see whether the exact same solution works for you, and what might be the differences (ex. .csproj reference with a HintPath).

**Comment by okvalsralos** [comment]
The solution you've attached compiles as is in release mode without any issues.
After I modify the solution to match as closely as possible to my project I can reproduce the issue.

To reproduce the same error try to change/force the property _Generate serialization assembly_ (project properties, build tab) from `Auto` to `On` and you get the same error as described.
Changing the setting to `Off` the project compiles. So the problem occurs with `Sgen.exe` (XML Serializer Generator Tool).

Adding `SecurityDriven.Inferno.dll` directly as a reference with  `Generate serialization assembly = On` the build succeeds.

**Comment by sdrapkin** [comment]
I tried setting _Generate serialization assembly_ to `On` in ConsoleApp1 tester, but could not reproduce your error. Our environments are probably different somehow.

I'm glad you found a way to get successful builds.

**Comment by okvalsralos** [comment]
The problem is mentioned in few different repositories also in the `dotnet/corefx` repository. More details in [#32457](https://github.com/dotnet/corefx/issues/32457).

For now I've created a new NuGet package in our local NuGet feed and included only `net462` version without any additional dependencies. Building in `Release` mode with `Generate serialization assembly = Auto` (or `On`) succeeds.
