### ISSUE TITLE
AesFactory.Aes othrows on Linux

### ISSUE THREAD

**Issue by mvacha** [sdrapkin/SecurityDriven.Inferno#31]
AesFactory.Aes by default calls `new AesCng()`, which throws `PlatformNotSupportedException` on Linux. 

It could call ` new AesCryptoServiceProvider` or `new AesManaged()` as both of these fallback to OpenSSL on Linux. Problem is neither of those are FIPS compliant on Linux/Mac (https://github.com/dotnet/runtime/issues/26037).

**Workaround:** replace call to `AesFactory.Aes` with `Aes.Create` (but loose FIPS compliance on Linux/Mac).

**Comment by sdrapkin** [comment]
@mvacha Thx for reporting this issue. Please review commit 6174f0a5e0e51c74574a5a670e0e776c14359b4c, or even test it in your Linux environment.

**Comment by WolfspiritM** [comment]
I have a similiar problem for Window with .NET Core. The .NET Standard version doesn't seem to work and the workaround won't work aswell cause it's windows.
I think that needs a switch for .netstandard in general:

```
System.TypeLoadException: Could not load type 'System.Security.Cryptography.AesCng' from assembly 'System.Security.Cryptography.Cng, Version=4.3.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
         at SecurityDriven.Inferno.Cipher.AesFactories.<>c.<.cctor>b__3_1()
         at SecurityDriven.Inferno.Cipher.AesCtrCryptoTransform..ctor(Byte[] key, ArraySegment`1 counterBufferSegment, Func`1 aesFactory)
```

**Comment by sdrapkin** [comment]
@WolfspiritM Can you confirm that the 6174f0a5e0e51c74574a5a670e0e776c14359b4c fix will resolve this issue for you?
