### ISSUE TITLE
Strong Name of 1.6.2

### ISSUE THREAD

**Issue by mikedoerfler** [sdrapkin/SecurityDriven.Inferno#32]
Good morning/afternoon/evening Stan, would you consider releasing a 1.6.2 update to Inferno.StrongName?  I've found issue #6 and #26 that indicate this is something you would be willing to do.

If you have a build automation script you use that you would commit I'd be willing to take a shot at it.

**Comment by sdrapkin** [comment]
@mikedoerfler Hi Mike, thanks for the reminder. It's probably time for v1.6.3, and I have a Linux bug-fix to include in it, so I'll try to sign the v1.6.3 (and keep signing all vNext versions). I'll ping you once the latest signed version is on Nuget.

**Comment by sdrapkin** [comment]
@mikedoerfler Attached is v1.6.3 (signed). It currently takes a dependency on a preview-version of [SRCS.Unsafe](https://www.nuget.org/packages/System.Runtime.CompilerServices.Unsafe/5.0.0-preview.3.20214.6). I will update Nuget once this dependency is out of preview.

[Inferno.1.6.3.nupkg.zip](https://github.com/sdrapkin/SecurityDriven.Inferno/files/4617610/Inferno.1.6.3.nupkg.zip)

**Comment by sdrapkin** [comment]
Nuget is updated with v1.6.3.
