### ISSUE TITLE
Unable to use Inferno on MacOS or Linux

### ISSUE THREAD

**Issue by loligans** [sdrapkin/SecurityDriven.Inferno#37]
@sdrapkin I ran into an issue while on MacOS where I cannot use the NETStandard library due to a bcrypt.dll reference missing. 

I was able to fix it by hacking up CryptoRandom with `RNGCryptoServiceProvider`. I simply replaced `CryptoRandom.NextBytes` with `RNGCryptoServiceProvider.GetBytes`.

**Comment by sdrapkin** [comment]
@loligans Thanks for reporting this issue. Making `CryptoRandom` work on non-Windows platforms is among the improvements I plan to implement.

**Comment by mrNo0b** [comment]
I think there should be message in readme/nuget info to inform users that it will not work on Linux etc, I used it to build web api .net 5 license system only to find out that problem after I deployed it to Heroku...
I use `SuiteB.Encrypt()`
had to change all the code, then I found this Issue and tried **loligans** solution and it seems to work now, CryptoRandom class was removed, hope it still got some security left in it 😄.
Some kind of official quick fix would be nice...

**Comment by wmate** [comment]
Hi folks, we also are running into this issue (used for linux/windows encryption interop). @loligans what would it take to convince you to submit a pull request? ;)

That might help @sdrapkin and in the meantime help out us community folks who may not be as comfortable ensuring our implementations of randomness are random enough.

**Comment by loligans** [comment]
I wouldn't mind submitting a PR but I don't think my fix would meet the Inferno standards when it comes to security.

**Comment by sdrapkin** [comment]
Inferno [v1.6.4](https://www.nuget.org/packages/inferno) was released on Nuget - should fix this issue.
