### ISSUE TITLE
Why can AesCtrCryptoTransforms not be reused?

### ISSUE THREAD

**Issue by TimmSkiller** [sdrapkin/SecurityDriven.Inferno#38]
I had a look in the source and `CanReuseTransform` is always set to `false`. Maybe there is a more technical reason as to why it's like this, I don't know.

**Comment by sdrapkin** [comment]
@TimmSkiller `CanReuseTransform` is set to `false` for several reasons:

- The transforms are stateful (ex. track current chunk number), and `ICryptoTransform` does not support a "Reset" API.
- The transforms are initialized with a `key` and a `salt`, and these parameters should never be reused for another stream.

HTH

**Comment by TimmSkiller** [comment]
I see. Thank you for clarifying!
