### ISSUE TITLE
SuiteB Encryption/Decription of data does not match

### ISSUE THREAD

**Issue by ItSkary** [sdrapkin/SecurityDriven.Inferno#41]
Greetings, 
probably i mistakenly used some API but i have followed example of code usage, and try to test latest version of the library (version 1.6.4, the latest on nuget) to crypt/decrypt some data.

Here the dummy example i have write to test how to use library :  

```
            byte[] key = new byte[] {97,98,99};
            string text = "text";

            var encr = SuiteB.Encrypt(key, text.ToBytes().AsArraySegment()).ToB64();
            var decr = SuiteB.Decrypt(key, encr.FromB64().AsArraySegment());
```

![image](https://user-images.githubusercontent.com/6507710/186182155-39fc04c9-fe19-4ce8-b923-a1026c3243e6.png)

As you can see decryption seems to attach empty character after each character of the plain text : 
'text' -> 't\0e\0x\0t\0'

Here how i have installed the library : 
![image](https://user-images.githubusercontent.com/6507710/186181506-17ea3c51-e405-4e6f-a319-d790a7a8c56a.png)

Have i missused some configuration/API?

**Comment by sdrapkin** [comment]
```csharp
byte[] key = new byte[] { 97, 98, 99 };
string text = "text";

var encr = SuiteB.Encrypt(key, text.ToBytes().AsArraySegment()).ToB64();
var decr = SuiteB.Decrypt(key, encr.FromB64().AsArraySegment()).FromBytes();

Console.WriteLine(decr);
```

**Comment by ItSkary** [comment]
Ah thank a lot. Tomorrow I will test it, but I have no doubt that my misunderstanding is the cause of the issue.
Thanks again for the clarification and swift answer

**Comment by ItSkary** [comment]
I can confirm adding FromBytes() solve the issues
