### ISSUE TITLE
Support encryption/decryption through TPM

### ISSUE THREAD

**Issue by ItSkary** [sdrapkin/SecurityDriven.Inferno#42]
Recently with Windows 11 Microsoft has made mandatory the use of TPM. 
I would like to know if there is some plan to implement some Inferno API to TPM, to easily encrypt/decrypt things using the device as password.

**Comment by sdrapkin** [comment]
Microsoft Research has an experimental TPM-Software-Stack (TSS) implementation: https://github.com/Microsoft/TSS.MSR, which claims to offer TPM services for secure cryptographic key generation & management.

Inferno does not concern itself with key-management, which is outside its scope.

**Comment by ItSkary** [comment]
Wow really precious information, I really miss the existence of this .Net library.
Thanks a lot for pointing out.
