### ISSUE TITLE
Appending content to an already encrypted file with EtM_EncryptTransform

### ISSUE THREAD

**Issue by henning-krause** [sdrapkin/SecurityDriven.Inferno#5]
I ran into an issue when I tried to append data to an already encrypted file using a new transform with the same key and the correct chunk number:

       private static void Main(string[] args)
        {
            var key = Encoding.ASCII.GetBytes("fooBar");
            var tempStream = new MemoryStream();
            var buffer = new byte[EtM_Transform_Constants.INPUT_BLOCK_SIZE];
            uint chunkNumber;
            byte[] content;
            using (var transform = new EtM_EncryptTransform(key))
            using (var crypto = new CryptoStream(tempStream, transform, CryptoStreamMode.Write))
            {
                crypto.Write(buffer, 0, buffer.Length);
                crypto.Write(buffer, 0, buffer.Length);
                crypto.FlushFinalBlock();
                var temp = new MemoryStream();
                temp.Write(tempStream.ToArray(), 0, (int) tempStream.Length);
                tempStream = temp;
                chunkNumber = transform.CurrentChunkNumber+1;
            }

            using (var transform = new EtM_EncryptTransform(key, chunkNumber: chunkNumber))
            using (var crypto = new CryptoStream(tempStream, transform, CryptoStreamMode.Write))
            {
                crypto.Write(buffer, 0, buffer.Length);
                crypto.Write(buffer, 0, buffer.Length);
                crypto.FlushFinalBlock();
                content = tempStream.ToArray();
            }

            var output = new MemoryStream();
            using (var transform = new EtM_DecryptTransform(key))
            using (var stream = new CryptoStream(new MemoryStream(content), transform, CryptoStreamMode.Read))
            {
                stream.CopyTo(output);

                Console.Out.WriteLine(output.Length + ":" + 4*buffer.Length);
            }
        }

This code throws a Cryptographic Exception with the text "Decryption failed for block 3."

I then changed the TransformFinalBlock method of the EtM_*Transform methods. I added this line at the start of each transform:

    if (inputCount == 0) return new byte[0];

And I changed this code in my test program:

    chunkNumber = transform.CurrentChunkNumber+1;

to 

    chunkNumber = transform.CurrentChunkNumber;

Now the code works. 

Would you say this is the correct approach? Or did I introduce one or more vulnerabilities by adding these lines?

**Comment by sdrapkin** [comment]
It seems to me that what you're trying to do is not aligned with how EtM_EncryptTransform is designed. A single application of EtM_EncryptTransform will generate N chunks, of which 1..N-1 chunks are of length 84928 and the last chunk of length strictly less than 84928 (let's call it LC for Last Chunk). Once you have a chunk with length less than 84928 in your stream, you cannot append any subsequent chunks to it. If you do, then LC will appear to have length larger than its true length, and you will get a decryption error in that chunk.

There is no need to change or substitute an EtM_EncryptTransform mid-stream. Keep writing to it as your plaintext comes in. If you're trying to freeze or pause the encryption (ex. you expect days/weeks to pass until the next piece of plaintext stream becomes available) and restart it later - ie. by storing the state somewhere other than memory, there is no support for that. CryptoStream itself would need such "hydration/dehydration" or "serialization/deserialization" support, which Microsoft doesn't provide. Ie. the crypto streams are intended to live in memory, and get cleaned up (ie. disposed) only once the end of the stream is signaled (at least that's how MS designed them).

Let me know if this provides some insight into what you're observing.

**Comment by henning-krause** [comment]
Thanks for the insights... that helped. I've solved the issue now using another way.
