### ISSUE TITLE
Provide strong-named assembly in nuget package

### ISSUE THREAD

**Issue by henning-krause** [sdrapkin/SecurityDriven.Inferno#6]
Could you strong-name the assembly you provide in the nuget package?

That would be awesome :-)

**Comment by sdrapkin** [comment]
Of course I could, but the real question is "should I?"

There seems to be a 'holy war' on whether strong-naming published assemblies is a good idea or not.
https://github.com/octokit/octokit.net/issues/405
https://github.com/octokit/octokit.net/issues/405#issuecomment-41643438
http://jeremydmiller.com/2014/04/28/fubumvc-lessons-learned-strong-naming-woes-and-workarounds/

Based on my cursory understanding, the "for SN" crowd are mostly users and somewhat less experienced folks, and the "against SN" crowd are mostly library/framework authors, hybrid author/user types, and somewhat more experienced folks who have run into all kinds of problems.

The main "for SN" argument seems to be convenience - ie. "don't make me do the SN myself". The main "against SN" argument seems to be "if you do it, you're signing up for all kinds of problems and pain down the road, so don't do it".

I'm not sure I'm ready to take sides :-)

**Comment by henning-krause** [comment]
Hmm.. never had issues with strong-named assemblies. However, people trying to use your nuget package will fail if their projects require strong naming. 

On the other hand, a project not requiring a strong name has no problems using a nuget package which has one.

Now I'm in the position of the first group and I thus cannot use it, which is somewhat unfortunate because now I don't get the benefit of nuget auto-updates....

**Comment by sdrapkin** [comment]
Can you share why your project requires strong naming? (not to question it - it just does, I get it - but to have valuable user feedback)

Once an assembly is strong named, you code will strongly bind to a particular version. I don't think you will get the NuGet auto-update benefit you're expecting. Once a newer version gets pushed to NuGet, you're likely to experience [binding problems](http://blog.davidebbo.com/2011/01/nuget-versioning-part-3-unification-via.html). What are your thoughts on that?

**Comment by DavidR91** [comment]
I feel like this should be re-evaluated. 

Strong naming is very common for 

* ASP .NET precompilation
* Various obfuscation + protection tools

I maintain a large commercial ASP .NET product, and literally all of its NuGet dependencies ship strong named assemblies, which means they can fit into our toolchain.

I **want** to use Inferno - however, without a shipped strong name version, we cannot build + protect our product. The lack of a strong name is a deal breaker for us

**Comment by sdrapkin** [comment]
@DavidR91 Is [self-signing](https://msdn.microsoft.com/en-ca/library/xc31ft41(v=vs.110).aspx) the Inferno assembly with your own key as part of the build process an option? One could even [HTTP-download](https://www.nuget.org/api/v2/package/Inferno/) the Nuget package, unzip, and commandline-sign in a few batch/powershell/LinqPad lines.

But I understand the PITA.

I will be releasing Inferno 1.4 soon. It will include an additional strong-name Nuget package available as well. Reopening this issue to keep everyone updated.

**Comment by DavidR91** [comment]
A separate strong-named NuGet package is great news, and a good compromise

+ I also totally understand the reluctance to ship it strong named default because the issues you listed (and personally, if I could avoid SN'ing out product I would, but the processing steps for precompile + obfuscation require it)

**Comment by DavidR91** [comment]
Just a note by the way - you can't use the `ildasm` or other tricks to strong name the current assembly because of the`InternalsVisibleTo` declaration 

`[assembly: InternalsVisibleTo("SecurityDriven.Inferno.Tests")]`

(a public key is apparently required if the internals visible to declaration remains)

**Comment by sdrapkin** [comment]
Inferno 1.4 has been released. `Inferno.StrongName` has also been published on Nuget.
[https://www.nuget.org/packages/inferno.strongname](https://www.nuget.org/packages/inferno.strongname).

Please try out `Inferno.StrongName`, and provide your feedback on whether it meets your needs (and this issue can be closed).

**Comment by DavidR91** [comment]
This is brilliant and works exactly how we need (+ how others using ASP .NET + obfuscators etc. will need)

Thank you very much for responding to and implementing this change, your library is awesome 👍
