### ISSUE TITLE
AllowOnlyFipsAlgorithms is useless?

### ISSUE THREAD

**Issue by Alxandr** [sdrapkin/SecurityDriven.Inferno#7]
As far as I can tell, `internal static readonly bool AllowOnlyFipsAlgorithms = true; // cache the FIPS flag` is completely useless. It's both internal, and readonly, meaning there is no way any external code (ie., consumers of Inferno) can change it. Doesn't that mean that all of your `Utils.AllowOnlyFipsAlgorithms ? A : B` are just a waste of computational power? I'm not saying it's a bottleneck or anything (it's probably not even registered on perf at all), just pointing out that the design seems weird to me.

**Comment by sdrapkin** [comment]
Hi Alxandr, thanks for looking at the code. Let me explain the rationale for having this flag as a variable. The built-in .NET equivalent of this flag is `System.Security.Cryptography.CryptoConfig.AllowOnlyFipsAlgorithms` which is also read-only. While this Inferno flag has no impact on compiled Inferno library, having this flag allows easy testing of performance differences between managed and unmanaged FIPS-certified implementations. It will also allow someone who only processes very short messages/data, does not require FIPS certification, and needs maximum performance to switch this flag to `false` (via a code change) and get a certain perf boost for their custom scenario.

**Comment by Alxandr** [comment]
Shouldn't it rather be an `#if`-def then? So you could remove all the internal `Func<Alg>` that is unused and can't be used, and if you want to test (and have to change code anyways) you can change a definition `ONLY_FIPS` or something?

**Comment by sdrapkin** [comment]
Unnecessary `#if/#endif` blocks make it difficult to reason about correctness of code by introspection, which is especially important for crypto libraries. Ex. OpenSSL suffers a great deal from `#ifdef` blocks that make it difficult to follow the logic.

Could the same effect be achieved via `#if/#endif`? Yes. Would it make for cleaner code? IMHO, no.

**Comment by Alxandr** [comment]
Fair enough. At least now I understand the point of what is essentially (from a distributed-as-a-library standpoint) pointless piece of code. It's intended for consumption when you consume the code in source code, rather than the assembly. Thank you for answering my question :).

On a side-note, for fun (and trying to learn a bit), I "ported" your code to a DNX project, that makes it work on .NET Core. Had to change a good deal of stuff though (and even drop some functionality) cause of lacking support for the crypto classes you use from the .NET framework in .NET Core. You can take a look at it if you like over at here: https://github.com/YoloDev/YoloDev.Skiba

**Comment by rodesh** [comment]
Please reconsider your decision to make this a hard-coded internal readonly.  In the built-in .NET equivalent, while the property is readonly (but public), it is controllable by setting the system FIPS policy and configuring whether to enforce the policy in the .NET application config.

I would love to use your library in a project I'm working on, however for reasons beyond my control, I cannot take a source-dependency on your project, and can only take a dependency on your pre-built library distributed from NuGet.

I do not have any need for FIPS Certification.  The up to 40x performance penalty (measured against our workload)  of the FIPS-certified implementations over their XXXXManaged counterparts, is a price too steep for me to pay.

**Comment by sdrapkin** [comment]
@rodesh FIPS-based crypto-primitive implementations make some scenarios faster-performing and other scenarios slower-performing: it depends on a particular workload. Let's assume for this discussion that no one (myself included) cares about FIPS conformance - correctness and performance are the only goals.

Your particular workload incurs 40x performance hit under FIPS. Inferno's primary usecase - streaming AEAD - incurs a 66% performance hit *without* FIPS.

I would normally advise compiling from source, but you can't take a source dependency. However, I hope you can still use c# and Reflection. Do the following before calling any other Inferno methods:

```c#
	var allowFips = typeof(SecurityDriven.Inferno.Utils).GetField("AllowOnlyFipsAlgorithms", BindingFlags.Static | BindingFlags.NonPublic);
	allowFips.GetValue(null).Dump();
	allowFips.SetValue(null, false);
	allowFips.GetValue(null).Dump();

**Comment by rodesh** [comment]
Thanks. Not sure how I overlooked reflection.  Will try it out when I get a chance.
