### ISSUE TITLE
How to add additional authenticated data to AEAD

### ISSUE THREAD

**Issue by veikkoeeva** [sdrapkin/SecurityDriven.Inferno#8]
Hi!

Very interesting library! I'm currently doing self-studies with cryptography and came across your clean looking library with clear principles listed. I'm not sure if this question belongs here or some other forum, such as Stackoverflow, but here goes.

I'm currently learning AEAD with additional authenticated data, AAD, or AD, as mentioned also at [SecurityDriven.Inferno site](http://securitydriven.net/inferno/). It looks like something goes wrong, since in the following `aeadWithAad` is zero length. Moreover, I'm not exactly sure if the following is the right way to achieve storing authenticated metadata so that if the data is saved, based on the data I can use it to choose the right key to decrypt the contents, naturally first only checking the hash, preferably without first reading all the contents.

I'm not sure if this questions belongs here or some other forum (Stackoverflow?). A bit premature perhaps, but do you accept PRs, say, for tests? If it makes sense, I can in time turn this question to a test.

```
using SecurityDriven.Inferno;
using System;
using System.IO;
using System.Security.Cryptography;
using System.Text;


namespace Test
{
    public static class Program
    {       
        public static void Main()
        {            
            const string toBeEncrypted1 = "ThisIsTheText1";
            const string toBeEncrypted2 = "ThisIsTheText2";

            var aeadWithAad = Encrypt(toBeEncrypted1, ChooseKey(0), "0|||");
            var aeadWithAadString = Convert.ToBase64String(aeadWithAad);

            Console.WriteLine(aeadWithAadString);            
        }


        private static byte[] Encrypt(string contentsToBeEncrypted, string theEncryptionKey, string additionalAuthenticatedData)
        {
            using(var plainTextStream = new MemoryStream(Encoding.UTF8.GetBytes(contentsToBeEncrypted)))
            {
                plainTextStream.Seek(0, SeekOrigin.Begin);
                using(var encryptedStream = new MemoryStream())
                {
                    var aadBytes = Encoding.UTF8.GetBytes(additionalAuthenticatedData);
                    var aadData = new ArraySegment<byte>(aadBytes, 0, aadBytes.Length);
                    using(var encTransform = new EtM_EncryptTransform(Encoding.UTF8.GetBytes(theEncryptionKey), aadData))
                    {
                        using(var cryptoStream = new CryptoStream(encryptedStream, encTransform, CryptoStreamMode.Write))
                        {
                            plainTextStream.CopyTo(cryptoStream);
                            cryptoStream.Flush();
                            encryptedStream.Flush();
                            plainTextStream.Flush();
                            return encryptedStream.ToArray();
                        }
                    }
                }
            }
        }


        private static string ChooseKey(int keyChooser)
        {
            const string theEncryptionKey1 = "TheSecretEncryptionKey1";
            const string theEncryptionKey2 = "TheSecretEncryptionKey2";
            const string theAuthenticationKey1 = "TheSecretOrPublicAuthenticationKey1";
            const string theAuthenticationKey2 = "TheSecretOrPublicAuthenticationKey2";

            if(keyChooser == 0)
            {
                return theAuthenticationKey1;    
            }
            else if(keyChooser == 1)
            {
                return theAuthenticationKey2;
            }

            throw new ArgumentOutOfRangeException(nameof(keyChooser));
        }
```

**Comment by sdrapkin** [comment]
@veikkoeeva Thank you for your comments - I'm glad you find [Inferno](http://SecurityDriven.NET/inferno/) interesting. The issue you are running into has to do with what `cryptoStream.Flush()` does:
```
public override void Flush()
{
}
```

I.e. it does nothing (Microsoft's code). `cryptoStream.Dispose()`, on the other hand, does something useful - namely calling `cryptoStream.FlushFinalBlock()`. You can either change your code to call `FlushFinalBlock()` instead of `Flush()` (which I don't like), or simply move the `return encryptedStream.ToArray()` statement outside the `using (var cryptoStream ..)` block.

If you follow the examples in Inferno's [documentation](http://securitydriven.net/inferno/#AEAD%20Transform%20%28Streaming%29), you will notice that `Flush()` is not called anywhere (not necessary).

**Comment by veikkoeeva** [comment]
@sdrapkin Oh, you were quick! Thanks, it really helped! Heh, I fell for the old-fashioned one...

Can I take your time a bit still and ask what would be the proper way to add plain-text, authenticated metadata? Now that I made some progress, it appears I have no success in adding that. For instance, that `0|||` would be `0x48 0x128 0x128 0x128`, but I don't see it anywhere in `aeadWithAad`. If one desires to do such a thing, should AEAD be constructred from the primitives?

**Comment by sdrapkin** [comment]
@veikkoeeva Good question. I don't think there is a "proper way" - it really depends on individual scenarios. It probably makes sense to send the AD before the AE (ie. prepend rather than append), since you'll need AD to start decryption. How you pass the AD payload along with AEAD (or whether you pass it at all, rather than, say, calculate it or extract it from some other data, ex. IP) is out of scope for AEAD (responsibility of those using AEAD for some particular purpose).

For variable-length AD I can suggest constructing AD as [AD length] || [AD content]. Sample code:
```c#
using (var ms = new MemoryStream())
{
	using (var msWriter = new BinaryWriter(ms, SecurityDriven.Inferno.Utils.SafeUTF8))
	{
		msWriter.Write("associated data");
	}
	ms.ToArray().Dump();
}
```
The only primitive you need is byte concatenation :relieved:

**Comment by veikkoeeva** [comment]
I suppose you are right. I interpreted the the part <blockquote>The EtM Encrypt/Decrypt transforms implement chunked authenticated encryption, and can wrap any .NET stream. Each chunk is independently keyed and authenticated. The "salt" parameter can include Additional Data (AD) or its hash - which will also be authenticated.</blockquote>

to mean I can do something like this:

1. Encrypt plain-text *P* using AES and a secret key *K*, using good *IV* to get cipher-text *C*.
2. Append *C* to *IV* and get *C2*, C2 = IV || C.
3. Prepend plain-text *Pt* to C2, get ADC3 = Pt || C2.
4. Use key *K2*, calculate *MAC* = HMAC(K2, ADC3).
5. Append MAC to ADC3, *ADC4* = ADC3 || MAC.

If that is a sensible thing to do, I can in time turn it into a test and do a PR if that's OK (I don't mind you doing that either if it'd be less of a hassle).

**Comment by sdrapkin** [comment]
@veikkoeeva The sensible thing to do is to use an existing, trusted AEAD library like Inferno (which is the very purpose of Inferno) - not a custom implementation. If you are thinking about working with IVs, MACs, and key derivations directly, you would be doing the very thing that Inferno is designed to avoid.

**Comment by veikkoeeva** [comment]
@sdrapkin Indeed it is, but I understood it's not directly possible. Or maybe I understood your example wrong. Do you mean use Inferno's AEAD *as usual*, then pre-pend a plain-text header which the reader can use with out-of-band information to choose the right decryption key and then have a MAC over it all one more time and have prepended too?

**Comment by sdrapkin** [comment]
@veikkoeeva I am assuming that all you are trying to do is to send the AD content along with the AEAD  ciphertext. A trivial code sample might be:

```c#
var mk = new byte[] { 1, 2, 3 };
var message = Utils.SafeUTF8.GetBytes("my secret message").AsArraySegment();
var ad = Utils.SafeUTF8.GetBytes("my associated data").AsArraySegment();
var adLength = ad.Count();

var aead = SuiteB.Encrypt(masterKey: mk, plaintext: message, salt: ad);
var ad_and_aead = Utils.Combine(ad.Array, aead);

var decryptedMessage = SuiteB.Decrypt(
	masterKey: mk,
	ciphertext: new ArraySegment<byte>(ad_and_aead, adLength, ad_and_aead.Length - adLength),
	salt: new ArraySegment<byte>(ad_and_aead, 0, adLength));

Utils.SafeUTF8.GetString(decryptedMessage).Dump(); // "my secret message"
```
Note that there is no need to MAC anything all-over/again. If you modify any bit in the `ad_and_aead` byte array, the decryption will fail.

**Comment by veikkoeeva** [comment]
@sdrapkin Ah, this works. I tried stubbornly use the streams and couldn't make it work. I need to thank you again. I think I can safely close this now and keep on prodding.

(Sorry for being slow, Mother's Day and all...)
