### ISSUE TITLE
[Question] Storing passwords with PBKDF2 and HKDF

### ISSUE THREAD

**Issue by Alxandr** [sdrapkin/SecurityDriven.Inferno#9]
Not sure you want questions about usage here, but I tried to ask over at StackOverflow and it didn't get any answers within a few hours, which in my experience means there is a high probability of it not being answered, so I figured I'd ask here as well. Also, you probably know this stuff better than the average StackOverflow user :P. The original post can be found [here](http://stackoverflow.com/questions/38519807/password-hashing-using-pbkdf2-and-hkdf-in-net), but I'm copying it in here for simplicity.

I've been tasked with the task of writing a new method for computing password hashes to replace the old one which we do not feel is sufficiently secure yet. A good while ago, I read the book Security Driven .NET, in which I learned that the important part is to use a algorithm with configurable amount of revolutions (as opposed to a simple hash), and that in .NET the recommended one was called `PBKDF2` for password handling. I also read that as an improvement to how ASP.NET deals with passwords, it would be nice if the resulting hash stored in the database was cryptographically tied to the user (either name or id) by way of using the PBKDF2 to create a master key, and then use the username (or id) to create a derived key using HKDF. But again, this is superficial knowledge that I read from a book that I do not currently have access to, so I can't recheck if my memory is correct.

Also, I've not used the .NET DerivedBytes APIs before, so I might be doing that wrong. So my question is this: Am I doing things right in the following code? Am I using the APIs correctly? And is this implementation "sufficiently secure"? Or am I doing something wrong which completely removes all of the security?

```csharp
    protected override byte[] ComputeHash(string user, string salt, string password)
    {
        var userBytes = user.ToBytes();
    ​
        using (var pbkdf2 = new PBKDF2(MacFactories.HMACSHA512, password.ToBytes(), salt.ToBytes()))
        {
            var masterKey = pbkdf2.GetBytes(128);
            using (var hkdf = new HKDF(MacFactories.HMACSHA512, masterKey, userBytes, userBytes))
            {
                return hkdf.GetBytes(64);
            }
        }
    }
```

**Comment by sdrapkin** [comment]
@Alxandr I've answered your original post on StackOveflow. You can also email me if you have other questions.

**Comment by Alxandr** [comment]
Thanks a bunch :)
